export const TOGGLE_MENU = 'TOGGLE_MENU';
export const REPORT_WINDOW_WIDTH = 'REPORT_WINDOW_WIDTH';
export const REPORT_WINDOW_HEIGHT = 'REPORT_WINDOW_HEIGHT';
export const REPORT_SCROLL_TOP_Y = 'REPORT_WINDOW_SCROLL';
export const SET_PHOTO_AT_CENTER = 'SET_PHOTO_AT_CENTER';






